#default_consistency/config.yaml
replication:
  strategy: NetworkTopologyStrategy
  datacenters:
    datacenter1:
      replication_factor: 6
      nodes:
        - "192.168.1.100"
        - "192.168.1.101"
        - "192.168.1.102"
        - "192.168.1.103"
        - "192.168.1.104"
        - "192.168.1.105"
        - "192.168.1.106"
        - "192.168.1.107"
    datacenter2:
      replication_factor: 4
      nodes:
        - "192.168.1.108"
        - "192.168.1.109"
        - "192.168.1.110"
        - "192.168.1.111"
        - "192.168.1.112"
        - "192.168.1.113"
        - "192.168.1.114"
        - "192.168.1.115"
    datacenter3:
      replication_factor: 5
      nodes:
        - "192.168.1.116"
        - "192.168.1.117"
        - "192.168.1.118"
        - "192.168.1.119"
        - "192.168.1.120"
        - "192.168.1.121"
        - "192.168.1.122"
        - "192.168.1.123"

# STCC-specific
delta_threshold_ms: 200

consistency_modes:
  enable_monotonic_read: true
  enable_monotonic_write: true
  enable_read_your_write: true
  enable_write_follow_read: true
  enable_user_generated_dependency: true

# Logging
log_path: "logs/ops_log.db"
